# Makefile for Beehive Monitoring System
#
# Toplevel makefile
#
# (c) Evangelos Rokas, 2016, 2017
#

#
# When flashing device with ARDUINOISP use BOARD_TAG 'bb8isp'
# when using serial flash with FTDI chip use tag 'bb8'
#


ARDUINO_SRC_VERSION	= 1.8.1
ARDUINO_SRC_DIR		= arduino-$(ARDUINO_SRC_VERSION)


#initialize programmer params
ISP_PORT	= /dev/ttyACM0
ISP_PROG	= stk500v1
AVRDUDE_ISP_BAUDRATE	= 19200

AVRDUDE_ARD_PROGRAMMER	= stv500v1

ARDUINO_PORT = /dev/ttyACM0
ARDUINO_DIR = $(ROOT_DIR)/$(ARDUINO_SRC_DIR)
#ALTERNATE_CORE = avr
ARDMK_DIR = $(ROOT_DIR)/Arduino-Makefile
